const c = require('fs').readFileSync('sasando_live_out/fig_sasando_live.html', 'utf8');
const iFn = c.indexOf('VERIFY_FN');
console.log('VERIFY_FN context in base demo:');
console.log(c.slice(iFn - 40, iFn + 140));
console.log('---');
const iVal = c.indexOf('VERIFY_VALUE');
console.log('VERIFY_VALUE context in base demo:');
console.log(c.slice(iVal - 30, iVal + 120));
console.log('---');
const iStatus = c.indexOf('live-root-fig_sasando_live-status');
console.log('status div context in base demo:');
console.log(c.slice(iStatus - 80, iStatus + 60));
