/** @vitest-environment happy-dom */
import { afterEach, expect, it, vi } from 'vitest'
import { createMarkdownRenderer } from '../src/markdown.js'
import { zhT } from './helpers/locale.js'

afterEach(() => {
  document.getSelection()?.removeAllRanges()
  document.body.replaceChildren()
  vi.restoreAllMocks()
})
it('renders XMarkdown synchronously, uses injected stream state and fully retires on dispose', () => {
  vi.spyOn(window, 'matchMedia').mockReturnValue({ matches: false } as MediaQueryList)
  const host = document.createElement('div')
  document.body.append(host)
  const renderer = createMarkdownRenderer(host, 'history', { part: 'body', streaming: true })
  expect(host.querySelector('[data-conversation-markdown="body"] p')?.textContent).toBe('history')
  expect(host.querySelector('.message-reveal-fragment')).toBeNull()
  renderer.update('history live', { streaming: true })
  expect(host.querySelector('.message-reveal-fragment')?.textContent).toBe(' live')
  renderer.update('history live **unfinished', { streaming: false })
  expect(host.textContent).toContain('**unfinished')
  renderer.dispose()
  expect(host.childNodes).toHaveLength(0)
  renderer.update('must stay retired')
  expect(host.childNodes).toHaveLength(0)
  renderer.dispose()
})
it('keeps the preview/static facade unanimated and synchronously releases the latest selection-held update', () => {
  const host = document.createElement('div')
  document.body.append(host)
  const renderer = createMarkdownRenderer(host, 'old')
  const paragraph = host.querySelector('p')
  const selection = document.getSelection()
  const range = document.createRange()
  range.selectNodeContents(paragraph ?? host)
  selection?.addRange(range)
  renderer.update('old backlog')
  renderer.update('old latest **answer**')
  expect(host.querySelector('p')).toBe(paragraph)
  expect(host.querySelector('strong')).toBeNull()
  selection?.removeAllRanges()
  document.dispatchEvent(new Event('selectionchange'))
  expect(host.querySelector('strong')?.textContent).toBe('answer')
  expect(host.querySelector('.message-reveal-fragment')).toBeNull()
  renderer.dispose()
})
it('copies genuine trailing code newlines exactly rather than stripping user content', async () => {
  const writeText = vi.fn().mockResolvedValue(undefined)
  Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText } })
  const host = document.createElement('div')
  document.body.append(host)
  const renderer = createMarkdownRenderer(host, '```\nline\n\n```')
  host.querySelector<HTMLButtonElement>('.code-copy')?.click()
  await Promise.resolve()
  expect(writeText).toHaveBeenCalledWith('line\n')
  renderer.dispose()
})
it('retains keyboard-accessible table regions, column header scope and alignment', () => {
  const host = document.createElement('div')
  document.body.append(host)
  const renderer = createMarkdownRenderer(host, '| key | value |\n| :--- | ---: |\n| a | 1 |', {
    t: zhT,
  })
  expect(host.querySelector('.table-scroll')?.getAttribute('tabindex')).toBe('0')
  expect(host.querySelector('.table-scroll')?.getAttribute('aria-label')).toBe('表格，可横向滚动')
  expect(host.querySelector('th')?.getAttribute('scope')).toBe('col')
  expect(host.querySelector('th:last-child')?.getAttribute('data-align')).toBe('right')
  expect(host.querySelector('td:last-child')?.getAttribute('data-align')).toBe('right')
  renderer.dispose()
})
